# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f8e9734f91137aa7af097739fbf6bcd5e2e6a052178ffba6d9736497f171a39c7a8528bb7ab0207b83d8895541bed69e1acef57778fa3560117ac93843f9648

test:
  secret_key_base: 199e855359419e6533b4fc86cad91a6f1bd1081d0b3cd68d0d76fa7741aa473b5b38edfd5486fdc0ebe21396ed5d77dbf76dd2724052bc43b92fb2086954a9c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
